export enum LATEST_CONTENT_ERROR_CODE {
  SOURCE_TEMPORARILY_UNAVAILABLE = 'SOURCE_TEMPORARILY_UNAVAILABLE',
  SOURCE_UNSUPPORTED = 'SOURCE_UNSUPPORTED',
  SOURCE_REQUEST_INVALID = 'SOURCE_REQUEST_INVALID',
}
