export enum LATEST_COMMENT_ERROR_CODE {
  SOURCE_UNSUPPORTED = 'COMMENT_SOURCE_UNSUPPORTED',
  SOURCE_REQUEST_INVALID = 'COMMENT_SOURCE_REQUEST_INVALID',
  SOURCE_TEMPORARILY_UNAVAILABLE = 'COMMENT_SOURCE_TEMPORARILY_UNAVAILABLE',
  SCORE_FILTER_UNSUPPORTED = 'COMMENT_SCORE_FILTER_UNSUPPORTED',
}
